<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unduh Silabus</name>
   <tag></tag>
   <elementGuidId>40e35305-1f9b-4dcf-8e5e-d5292ba48f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Unduh Silabus&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>221f2af1-5749-45cc-95d9-4ded06f64f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18a6e195-c0fe-49b3-a2f7-1f8410320870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-cerulean-600 text-cerulean-500 text-center hover:text-white border border-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none</value>
      <webElementGuid>bc077b4b-93f6-4986-bcf8-049af5993003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download</value>
      <webElementGuid>126434d4-c3c1-462d-9ed2-00047d98cb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>291da8a0-fe1f-42d4-b861-385fea097afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>d787366b-8786-4203-825a-e299801456e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unduh Silabus</value>
      <webElementGuid>ac15fde8-da70-40aa-88b6-3f901c670702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-detail-training&quot;)/div[@class=&quot;min-h-full&quot;]/main[@class=&quot;lg:px-[108px] px-9 lg:pb-24 pb-8 -mt-[300px] lg:-mt-[280px]&quot;]/div[@class=&quot;max-w-3xl mx-auto sm:px-6 lg:max-w-7xl lg:px-0&quot;]/div[1]/div[@class=&quot;grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-[50px]&quot;]/div[@class=&quot;grid grid-cols-1 lg:col-span-2&quot;]/section[1]/section[1]/div[@class=&quot;overflow-hidden bg-white rounded-lg shadow&quot;]/dl[@class=&quot;flex flex-wrap px-5 py-8 gap-y-4&quot;]/div[@class=&quot;grid w-full grid-cols-2 gap-5&quot;]/a[@class=&quot;hover:bg-cerulean-600 text-cerulean-500 text-center hover:text-white border border-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none&quot;]</value>
      <webElementGuid>3f9699e1-ac16-46ef-86b9-fd50d8c4cc25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>0e06cadf-891b-4da9-963b-063f8bc7218f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-detail-training']/div/main/div/div/div/div/section/section/div/dl/div[4]/a</value>
      <webElementGuid>94cb5771-a814-468b-8077-2668ee3acf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unduh Silabus')]</value>
      <webElementGuid>5afc628a-fec5-4f30-8712-71ac9d265f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>1f4b1dec-e83e-4266-96f7-f0c185b7757f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quint'])[1]/following::a[1]</value>
      <webElementGuid>651a9092-1105-4dcd-90c8-d227e7ae59ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>22d6e9bd-101f-4bfa-b797-d46f0d6c5a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unduh Silabus']/parent::*</value>
      <webElementGuid>aa72fc90-0deb-4bf8-9fc6-332a1ed605f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download')]</value>
      <webElementGuid>0a79c30a-8022-4eb4-bb07-96b108e215fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>360b946d-db40-4860-be37-415a82ee80f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @href = 'https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download' and (text() = 'Unduh Silabus' or . = 'Unduh Silabus')]</value>
      <webElementGuid>5528297b-909d-4eb8-8ca7-f3cebd7e3269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
