<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unduh Silabus</name>
   <tag></tag>
   <elementGuidId>40e35305-1f9b-4dcf-8e5e-d5292ba48f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Unduh Silabus&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0035c8ea-a1e8-4ec8-bef5-a98d8d532605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2907297c-ddca-42f6-a06a-60c8a7478946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-cerulean-600 text-cerulean-500 text-center hover:text-white border border-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none</value>
      <webElementGuid>4dd73c08-348e-4f1d-9412-42fc6e7ab46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download</value>
      <webElementGuid>61d99629-df6c-4a30-9501-f23584d8641b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>937c9519-1f3c-4d96-b616-3442ea764d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>3f4aa807-aac6-4f58-91ba-75142b851aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unduh Silabus</value>
      <webElementGuid>aeb09a69-2b1e-463d-a5e6-0c92fad482ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-detail-training&quot;)/div[@class=&quot;min-h-full&quot;]/main[@class=&quot;lg:px-[108px] px-9 lg:pb-24 pb-8 -mt-[300px] lg:-mt-[280px]&quot;]/div[@class=&quot;max-w-3xl mx-auto sm:px-6 lg:max-w-7xl lg:px-0&quot;]/div[1]/div[@class=&quot;grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-[50px]&quot;]/div[@class=&quot;grid grid-cols-1 lg:col-span-2&quot;]/section[1]/section[1]/div[@class=&quot;overflow-hidden bg-white rounded-lg shadow&quot;]/dl[@class=&quot;flex flex-wrap px-5 py-8 gap-y-4&quot;]/div[@class=&quot;grid w-full grid-cols-2 gap-5&quot;]/a[@class=&quot;hover:bg-cerulean-600 text-cerulean-500 text-center hover:text-white border border-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none&quot;]</value>
      <webElementGuid>a38d2bf9-6e6c-4bf3-960d-c6fb4b1dc54c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>32b4d54c-8572-418c-aa17-9900a66a8d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-detail-training']/div/main/div/div/div/div/section/section/div/dl/div[4]/a</value>
      <webElementGuid>d7160aae-8f58-4f24-a437-77ac5dc99c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unduh Silabus')]</value>
      <webElementGuid>443e5601-469b-47a1-a9c0-ee09df21e6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>e153182b-73ba-4540-b1ab-900f8fafac9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quint'])[1]/following::a[1]</value>
      <webElementGuid>d70f86e3-0dcc-41ff-87b9-ed0d434b4ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>db6a7034-8d3e-43a9-9542-0daa436e6d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unduh Silabus']/parent::*</value>
      <webElementGuid>bdabc842-ff05-42f5-85eb-5b39b4ff3b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download')]</value>
      <webElementGuid>92a86099-0602-400f-9bbf-5ed29daa3844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>1f6ea617-0416-4569-b7bb-257278bc038f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and @href = 'https://api.metrodataacademy.id/api/v2/training/public/courses/00aede58-497f-4868-9e34-dd301c2a0a83/syllabus/download' and (text() = 'Unduh Silabus' or . = 'Unduh Silabus')]</value>
      <webElementGuid>e680bd18-862e-4a1d-a031-00522a55fe88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
