<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>cf3cca21-7936-4192-ad0d-828990536f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Daftar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>336619a1-23ba-461c-86ca-1ddba113c187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>318165fd-98bd-4a75-b772-f957242be786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white bg-cerulean-600 hover:bg-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none</value>
      <webElementGuid>eabfa3c3-4f3e-4109-8ce7-252ace382584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>6a6990c2-d8d8-404d-8518-2d92b9ca926a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-detail-training&quot;)/div[@class=&quot;min-h-full&quot;]/main[@class=&quot;lg:px-[108px] px-9 lg:pb-24 pb-8 -mt-[300px] lg:-mt-[280px]&quot;]/div[@class=&quot;max-w-3xl mx-auto sm:px-6 lg:max-w-7xl lg:px-0&quot;]/div[1]/div[@class=&quot;grid grid-cols-1 items-start gap-4 lg:grid-cols-3 lg:gap-[50px]&quot;]/div[@class=&quot;grid grid-cols-1 lg:col-span-2&quot;]/section[1]/section[1]/div[@class=&quot;overflow-hidden bg-white rounded-lg shadow&quot;]/dl[@class=&quot;flex flex-wrap px-5 py-8 gap-y-4&quot;]/div[@class=&quot;grid w-full grid-cols-2 gap-5&quot;]/button[@class=&quot;text-white bg-cerulean-600 hover:bg-cerulean-500 focus:ring-4 focus:ring-cerulean-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none&quot;]</value>
      <webElementGuid>8fa61403-0856-4d04-b6cd-81e3fa917c77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>9d67efd4-0647-4220-b64c-ef8638f60a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-detail-training']/div/main/div/div/div/div/section/section/div/dl/div[4]/button</value>
      <webElementGuid>75552f27-4b0b-4e01-938f-bbc8e264ca22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh Silabus'])[1]/following::button[1]</value>
      <webElementGuid>cf0e9b3e-9d5f-4b68-af4d-431a7a42892f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::button[1]</value>
      <webElementGuid>774e274c-e82f-475e-ab7d-ee5bdadfce3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info.training@metrodata.co.id'])[1]/preceding::button[1]</value>
      <webElementGuid>3386e7ea-f637-4c3b-98b3-0db4a5c58def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>429fd0f6-0cb5-450a-828f-c6c85eeb8d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>6ade521f-d1b8-4631-9271-70a5285bb1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>4fd030cc-099a-4d21-ac90-c16f73550bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
