<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Metrodata Mengajar_absolute inset-0</name>
   <tag></tag>
   <elementGuidId>3efec0b0-fd97-43e6-b822-6f88d30b449b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/nav/div[3]/div/div/div/div[2]/div/div/div/div[2]/div[4]/div/div[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Global&quot;i >> internal:role=link[name=&quot;Metrodata Mengajar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48bc76bc-a87a-498d-824d-fe8874a0ac85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0</value>
      <webElementGuid>02ffed90-0668-4298-9d2f-bd8d0395d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;fixed top-0 left-0 right-0 z-10 bg-gradient-to-r from-white/40 to-white/20 sm:z-40 drop-shadow-lg backdrop-blur-lg&quot;]/nav[@class=&quot;flex items-center justify-between lg:px-[108px] xl:py-2 xl:h-[92px] py-6 px-8 xl:justify-center&quot;]/div[@class=&quot;items-center justify-center hidden mx-auto xl:flex xl:gap-x-5&quot;]/div[@class=&quot;flex flex-row gap-x-5&quot;]/div[@class=&quot;flex gap-x-5 group&quot;]/div[1]/div[2]/div[@class=&quot;absolute inset-x-0 top-0 bg-white shadow-lg -z-10 pt-9 ring-1 ring-gray-900/5 hidden group-hover:md:block hover:md:block&quot;]/div[@class=&quot;border-t-[1px] border-black/10 mt-14&quot;]/div[@class=&quot;flex flex-row justify-around px-20 py-10 max-w-7xl lg:px-[108px]&quot;]/div[@class=&quot;flex flex-wrap w-2/3&quot;]/div[@class=&quot;relative w-1/2 p-4 mb-4 -mt-4 text-sm leading-[17.5px] rounded-lg hover:bg-gray-50&quot;]/div[@class=&quot;flex flex-row&quot;]/div[@class=&quot;w-4/5 pl-4&quot;]/a[@class=&quot;block text-base font-semibold leading-5 text-gray-900 group-hover:hover:text-cerulean-600 group-hover:text-black&quot;]/span[@class=&quot;absolute inset-0&quot;]</value>
      <webElementGuid>460948d8-3249-430a-85ca-927e96619e77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/nav/div[3]/div/div/div/div[2]/div/div/div/div[2]/div[4]/div/div[2]/a/span</value>
      <webElementGuid>257ac547-6ce4-499a-842c-a0f80a166aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/a/span</value>
      <webElementGuid>b74b604a-6fd2-44a3-a763-17d674433784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
