<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>2d44954a-88b8-44eb-80b8-67a5f3aeb386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Daftar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85b7555a-3215-4b49-9bbc-b8232554c40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-cerulean-600 hover:bg-cerulean-700 transition duration-500 ease-linear px-5 py-4 rounded-md text-white text-base w-full mt-4 font-bold font-sans leading-normal</value>
      <webElementGuid>af3b8543-584a-4223-99c8-06ca9a03ff70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>0a8b8e32-881a-49b0-98c9-def9752533fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;grid justify-center grid-cols-3 gap-5 mx-9 lg:mx-[108px] -mt-[340px] lg:flex-row&quot;]/div[@class=&quot;col-span-3 lg:col-span-1 mt-[36px] lg:mt-0&quot;]/div[@class=&quot;flex flex-col gap-4 px-5 py-10 bg-white border-0 rounded-lg drop-shadow-lg&quot;]/button[@class=&quot;bg-cerulean-600 hover:bg-cerulean-700 transition duration-500 ease-linear px-5 py-4 rounded-md text-white text-base w-full mt-4 font-bold font-sans leading-normal&quot;]</value>
      <webElementGuid>a601a573-a90e-496d-979f-c081da51f00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>4c70c312-bc6c-4267-915d-ed9065fedffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengisi form feedback sesuai dengan nama dan email yang terdaftar'])[1]/following::button[2]</value>
      <webElementGuid>73fcd7b8-7d94-4f40-b3fe-a5e58226c3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengikuti tata tertib yang dibuat oleh penyelenggara'])[1]/following::button[2]</value>
      <webElementGuid>6eaa4048-b353-4798-8d39-86f4bddf57b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CyberSHEcurity: Empowering Women in Security'])[2]/preceding::button[1]</value>
      <webElementGuid>a1801e99-8f74-42be-a0e1-222b6a39c240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classroom'])[2]/preceding::button[1]</value>
      <webElementGuid>76628e3c-5416-4268-bb59-e6bc6f0b7361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>ec24ea1a-9e8e-4294-b702-4851e10593ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>0cb13ce7-6ccb-4c6d-b57a-bc6dfa9b5ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>743306dc-ee4f-494d-9566-885edde28ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
