<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phoneNumber</name>
   <tag></tag>
   <elementGuidId>61030f35-170b-416c-bcfc-8b358a6c8969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;81234567890&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0cfe084-f9a2-474a-ae4b-b8b636f8a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99a57848-c555-4659-8681-44f7f5523ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>0b6d5efc-6e7e-4b31-916c-d5025bee7c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>57e88dd4-4f41-421e-a878-7ee6986c6ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>81234567890</value>
      <webElementGuid>7ea6aec2-8d42-485a-bdcc-e0b65233a604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-[14px] bg-gray-50 border rounded-r-lg border-gray-300</value>
      <webElementGuid>2cbe5461-5bd6-40bc-8698-975772ffbd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumber&quot;)</value>
      <webElementGuid>070dc935-cfa1-4fa2-860a-6c5fc036260b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNumber']</value>
      <webElementGuid>3c79f602-a855-4462-a4d7-f52d8a4d84cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/form/div[3]/div/div/div/div/input</value>
      <webElementGuid>57a353de-0392-443d-b7e6-32edc8193f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>d1fb0430-90f6-438b-a96c-2678ff3d8424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'phoneNumber' and @id = 'phoneNumber' and @placeholder = '81234567890']</value>
      <webElementGuid>261fe006-d1f5-4709-81e9-7a255e901eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
